spring.datasource.url=jdbc:postgresql://localhost:5433/brewmaster_test
spring.datasource.username=brewmaster
spring.datasource.password=brewmaster

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false